// <auto-generated />
namespace S.S.L.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Schemachange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Schemachange));
        
        string IMigrationMetadata.Id
        {
            get { return "201806021935484_Schema change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
